
name: Release Ci

on:
  push:
      tags:
        - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps: 

      - name: Download | Download CI script 
        run: |
          curl -L -o ci.sh hhttps://github.com/initialencounter/napcat.nix/raw/refs/heads/master/linux-qq-patch.sh
          ls -la
          cat ci.sh
          
      - name: Build | Build Package
        run: |
          bash ci.sh

      - name: Name | Name Package
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          mv linux-qq-patch.deb linux-qq-patch_${TAG_NAME}.deb
          ls -la

      - name: Create Release Draft and Upload Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux-qq-patch_${{ env.TAG_NAME }}.deb
